//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExistencias
    {
        public string IdExistencias { get; set; }
        public string IdArticulo { get; set; }
        public System.DateTime FechaVence { get; set; }
        public int Cantidad { get; set; }
        public string Lote { get; set; }
    
        public virtual tblArticulos tblArticulos { get; set; }
    }
}
